FROM node:16-alpine

WORKDIR /app

COPY ./package.json ./
COPY ./backend/package.json ./backend/
COPY ./packages/auth/package.json ./packages/auth/
COPY ./packages/db/package.json ./packages/db/
COPY ./packages/schema/package.json ./packages/schema/
COPY ./yarn.lock ./
RUN yarn install
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

COPY ./backend ./backend
COPY ./packages ./packages
CMD [ "yarn","start" ]
