version: '3'

services:
  api:
    container_name: "api"
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - . :/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongo
  mongo:
   image: mongo
   container_name: "mongodb"
   restart: always
   volumes:
     - /mongoData:/data/db
   ports:
     - 27017:27017
